I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 99, in script
    b "Who are you?"
Exception: Sayer 'b' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 99, in script
    b "Who are you?"
  File "C:\Users\0megabeast_dev\Downloads\renpy-7.3.2-sdk\renpy\ast.py", line 676, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\0megabeast_dev\Downloads\renpy-7.3.2-sdk\renpy\ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'b' is not defined.

Windows-8-6.2.9200
Ren'Py 7.3.2.320
RnVjaw 1.0
Tue Sep 17 20:01:31 2019
